Chrome supports color emojis on some OS
bramstein/stateofwebtype pull request #19
Opened 2017-03-10 10:36 UTC by Crissov

- Chrome 53 added color emoji support on Windows 10+ in September 2016 http://caniemoji.com/microsoft-windows/
- Chrome 41 added color emoji support on OS X 10.10+ in March 2015 http://caniemoji.com/os-x/

Also: Firefox bundles Emojione now for color emoji support on older systems.

2017-03-10 19:18 UTC, RoelN commented on src/data/color-fonts.js
> +      { name: "chrome",  range: "53-",  support: "partial", note: "Only COLR/CPAL on Windows 8.1+ and OpenType-SVG on Windows 10+."},
On WIndows, COLR/CPAL works through `@font-face`, but OT SVG doesn't?

2017-03-10 19:18 UTC, RoelN commented on src/data/color-fonts.js
> +      { name: "chrome",  range: "53-",  support: "partial", note: "Only COLR/CPAL on Windows 8.1+ and OpenType-SVG on Windows 10+."},
On WIndows, COLR/CPAL works through `@font-face`, but OT SVG doesn't?

2017-03-11 08:55 UTC, Crissov commented on src/data/color-fonts.js
> +      { name: "chrome",  range: "53-",  support: "partial", note: "Only COLR/CPAL on Windows 8.1+ and OpenType-SVG on Windows 10+."},
Sorry, I only have a Windows 7 box to test right now.

2017-03-13 12:10 UTC, RoelN requested changes
This doesn't appear to be very well tested?

2017-03-13 12:10 UTC, RoelN commented on src/data/color-fonts.js
> +          { name: "chrome", range: "41-", support: "yes", note: "Only on OS X 10.10 or macOS 10.12 and above." },
Not for fonts loaded through `@font-face` though.

2017-03-13 12:10 UTC, RoelN commented on src/data/color-fonts.js
> +          { name: "chrome", range: "53-", support: "yes", note: "Only on Windows 10 and above." },
This doesn't seem to be the case, only COLR/CPAL works.

2023-08-22 21:16 UTC, closed without merging